In [1]:
import numpy as np

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
arreglo_1 = np.array(lista)
arreglo_2 = np.array([1,2,3])

print(type(arreglo_1))
print(type(arreglo_2))

print(arreglo_1)
print(arreglo_2)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
[1 2 3]


In [4]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz_1 = np.array(matriz)
print(matriz_1)
print(type(matriz_1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [5]:
print(matriz[0] + matriz[1])

[1, 2, 3, 4, 5, 6]


In [6]:
print(arreglo_1.dtype)
print(matriz_1.dtype)

int64
int64


In [7]:
print(arreglo_1.ndim)
print(matriz_1.ndim)

1
2
